esphome:
  name: pbhub_example
  platform: ESP32
  board: esp32dev

# Define the I2C bus
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

# Include the custom components
external_components:
  - source: local
    components: [m5unit_pbhub, pbhub_pin]

m5unit_pbhub:
  id: pbhub_component
  address: 0x38
  channel: 0

# Define the binary sensor using the custom PbHub pin
binary_sensor:
  - platform: pbhub_pin
    name: "RF433 Receiver"
    pin:
      m5unit_pbhub: pbhub_component
      number: 0
      mode: INPUT_PULLUP
      pullup: true
    id: rf_receiver
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

# Define the remote receiver using the custom PbHub pin
remote_receiver:
  - platform: pbhub_pin
    id: rf_receiver
    dump: all
    pin:
      m5unit_pbhub: pbhub_component
      number: 0
      mode: INPUT_PULLUP
      pullup: true
